# Inferno Helm Chart - Default Values
# Override with environment-specific values files (values-dev.yaml, values-prod.yaml, etc.)

# ============================================================================
# GLOBAL SETTINGS
# ============================================================================

# Namespace for deployment
namespace: default

# Environment: development, staging, production
environment: development

# Instance name for pod identification
instanceName: inferno

# ============================================================================
# IMAGE CONFIGURATION
# ============================================================================

image:
  repository: inferno
  tag: "0.8.0"
  pullPolicy: IfNotPresent

# Image pull secrets (for private registries)
imagePullSecrets: []

# ============================================================================
# DEPLOYMENT CONFIGURATION
# ============================================================================

# Number of replicas (overridden by HPA if enabled)
replicaCount: 3

# Deployment strategy
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

# Pod annotations
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9090"
  prometheus.io/path: "/metrics"

# Security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

# ============================================================================
# SERVICE CONFIGURATION
# ============================================================================

service:
  # Internal service
  internal:
    type: ClusterIP
    port: 8000
    targetPort: 8000
    name: inferno
    annotations: {}

  # External service
  external:
    enabled: true
    type: LoadBalancer  # Change to NodePort if no cloud LB
    port: 80
    targetPort: 8000
    name: inferno-external
    annotations: {}
    externalIPs: []

# ============================================================================
# RESOURCE LIMITS & REQUESTS
# ============================================================================

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

# ============================================================================
# AUTOSCALING
# ============================================================================

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  
  # Metrics for scaling
  metrics:
    cpu:
      enabled: true
      utilization: 70
    memory:
      enabled: true
      utilization: 80

  # Scale behavior
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 50
          periodSeconds: 30
        - type: Pods
          value: 2
          periodSeconds: 30

# Vertical Pod Autoscaler (optional)
vpa:
  enabled: false
  updateMode: "Off"  # Change to "Auto" for automatic updates

# ============================================================================
# PERSISTENT STORAGE
# ============================================================================

persistence:
  enabled: true
  storageClass: standard
  
  # Models volume
  models:
    size: 100Gi
    path: /home/inferno/.inferno/models
  
  # Cache volume
  cache:
    size: 50Gi
    path: /home/inferno/.inferno/cache
  
  # Queue volume
  queue:
    size: 10Gi
    path: /home/inferno/.inferno/queue

# ============================================================================
# ENVIRONMENT VARIABLES (from ConfigMap & Secrets)
# ============================================================================

configMap:
  # Logging
  INFERNO_LOG_LEVEL: "info"
  INFERNO_LOG_FORMAT: "json"
  
  # API Configuration
  INFERNO_BIND_ADDRESS: "0.0.0.0"
  INFERNO_BIND_PORT: "8000"
  INFERNO_WORKER_THREADS: "4"
  INFERNO_REQUEST_TIMEOUT: "300"
  
  # Model Configuration
  INFERNO_MAX_MODEL_SIZE_GB: "50"
  INFERNO_CONTEXT_SIZE: "2048"
  INFERNO_BATCH_SIZE: "32"
  INFERNO_GPU_ENABLED: "true"
  
  # Queue Configuration
  INFERNO_QUEUE_MAX_PENDING: "1000"
  INFERNO_QUEUE_MODERATE_THRESHOLD: "70"
  INFERNO_QUEUE_CRITICAL_THRESHOLD: "90"
  INFERNO_MAX_WORKERS: "8"
  INFERNO_QUEUE_CHECKPOINT_INTERVAL: "30"
  
  # Profiling Configuration
  INFERNO_PROFILING_ENABLED: "true"
  INFERNO_PROFILING_MAX_PROFILES: "1000"
  INFERNO_INFERENCE_TIMEOUT: "300"
  INFERNO_TOKEN_TIMEOUT: "30"
  
  # Cache Configuration
  INFERNO_CACHE_STRATEGY: "hybrid"
  INFERNO_CACHE_SIZE_MB: "500"
  INFERNO_CACHE_TTL: "3600"
  INFERNO_CACHE_COMPRESSION_ENABLED: "true"
  
  # Streaming Configuration
  INFERNO_TOKEN_BATCH_SIZE: "3"
  INFERNO_TOKEN_BATCH_MAX_WAIT_MS: "50"
  INFERNO_KEEPALIVE_INTERVAL: "30"
  INFERNO_COMPRESSION_FORMAT: "auto"
  
  # Deployment Configuration
  INFERNO_ENV: "production"
  INFERNO_METRICS_ENABLED: "true"
  INFERNO_METRICS_PORT: "9090"

secrets:
  # Authentication (set via --set or -f values)
  INFERNO_AUTH_ENABLED: "false"
  INFERNO_AUTH_SECRET_KEY: ""
  
  # Optional: Sentry
  INFERNO_SENTRY_DSN: ""
  
  # Optional: OAuth2
  OAUTH2_CLIENT_ID: ""
  OAUTH2_CLIENT_SECRET: ""
  OAUTH2_PROVIDER_URL: ""

# ============================================================================
# HEALTH CHECKS
# ============================================================================

healthChecks:
  startup:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 3
    failureThreshold: 15
    successThreshold: 1
  
  readiness:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  
  liveness:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

# ============================================================================
# AFFINITY & TOPOLOGY
# ============================================================================

affinity:
  # Pod anti-affinity for distribution
  podAntiAffinity:
    preferred: true  # Set to false for strict anti-affinity
    topologyKey: kubernetes.io/hostname

# ============================================================================
# RBAC
# ============================================================================

rbac:
  create: true
  serviceAccountName: inferno

# ============================================================================
# NETWORK POLICY
# ============================================================================

networkPolicy:
  enabled: true
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8000
        - protocol: TCP
          port: 9090

# ============================================================================
# POD DISRUPTION BUDGET
# ============================================================================

podDisruptionBudget:
  enabled: true
  minAvailable: 2  # At least 2 pods must be available

# ============================================================================
# MONITORING & OBSERVABILITY
# ============================================================================

monitoring:
  prometheus:
    enabled: true
    port: 9090
    scrapeInterval: 30s

  # ServiceMonitor for Prometheus Operator (optional)
  serviceMonitor:
    enabled: false

  # PrometheusRule for alerts (optional, requires Prometheus Operator)
  prometheusRule:
    enabled: false

# ============================================================================
# INGRESS
# ============================================================================

ingress:
  enabled: false
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: inferno.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: inferno-tls
      hosts:
        - inferno.example.com

# ============================================================================
# NODE SELECTION
# ============================================================================

nodeSelector: {}

tolerations: []

# ============================================================================
# TERMINATION
# ============================================================================

terminationGracePeriodSeconds: 30

# ============================================================================
# INIT CONTAINERS (optional)
# ============================================================================

initContainers: []

# ============================================================================
# ENTERPRISE AUTHENTICATION & MULTI-TENANCY
# ============================================================================

auth:
  # OAuth2 Configuration
  oauth2:
    enabled: false
    session:
      ttl: 3600
      refresh_threshold: 300
      cookie:
        name: inferno_session
        secure: true
        http_only: true
        same_site: "Strict"
        domain: ""
        path: "/"
    token:
      validate_signature: true
      validate_expiration: true
      validate_audience: true
      validate_issuer: true
      clock_skew: 30
    redirect_uri_whitelist:
      - "http://localhost:8000/auth/callback"
      - "https://inferno.example.com/auth/callback"
    providers:
      google:
        enabled: false
        authorization_endpoint: "https://accounts.google.com/o/oauth2/v2/auth"
        token_endpoint: "https://oauth2.googleapis.com/token"
        userinfo_endpoint: "https://www.googleapis.com/oauth2/v2/userinfo"
        jwks_uri: "https://www.googleapis.com/oauth2/v3/certs"
        client_id: ""
        client_secret: ""
        redirect_uri: "https://inferno.example.com/auth/callback/google"
        scope: "openid profile email"
        user_claim_mappings:
          user_id: "sub"
          email: "email"
          name: "name"
        tenant_claim: ""
      github:
        enabled: false
        authorization_endpoint: "https://github.com/login/oauth/authorize"
        token_endpoint: "https://github.com/login/oauth/access_token"
        userinfo_endpoint: "https://api.github.com/user"
        client_id: ""
        client_secret: ""
        redirect_uri: "https://inferno.example.com/auth/callback/github"
        scope: "user:email read:org"
        user_claim_mappings:
          user_id: "id"
          email: "email"
          name: "name"
      okta:
        enabled: false
        authorization_endpoint: "https://${OKTA_DOMAIN}/oauth2/v1/authorize"
        token_endpoint: "https://${OKTA_DOMAIN}/oauth2/v1/token"
        userinfo_endpoint: "https://${OKTA_DOMAIN}/oauth2/v1/userinfo"
        jwks_uri: "https://${OKTA_DOMAIN}/oauth2/v1/keys"
        client_id: ""
        client_secret: ""
        redirect_uri: "https://inferno.example.com/auth/callback/okta"
        scope: "openid profile email"
        user_claim_mappings:
          user_id: "sub"
          email: "email"
          name: "name"
      auth0:
        enabled: false
        authorization_endpoint: "https://${AUTH0_DOMAIN}/authorize"
        token_endpoint: "https://${AUTH0_DOMAIN}/oauth/token"
        userinfo_endpoint: "https://${AUTH0_DOMAIN}/userinfo"
        jwks_uri: "https://${AUTH0_DOMAIN}/.well-known/jwks.json"
        client_id: ""
        client_secret: ""
        redirect_uri: "https://inferno.example.com/auth/callback/auth0"
        scope: "openid profile email"
        user_claim_mappings:
          user_id: "sub"
          email: "email"
          name: "name"
      azure:
        enabled: false
        authorization_endpoint: "https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/authorize"
        token_endpoint: "https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token"
        userinfo_endpoint: "https://graph.microsoft.com/v1.0/me"
        jwks_uri: "https://login.microsoftonline.com/${TENANT_ID}/discovery/v2.0/keys"
        client_id: ""
        client_secret: ""
        redirect_uri: "https://inferno.example.com/auth/callback/azure"
        scope: "openid profile email"
        user_claim_mappings:
          user_id: "sub"
          email: "mail"
          name: "displayName"
    secrets:
      google:
        client_id: ""
        client_secret: ""
      github:
        client_id: ""
        client_secret: ""
      okta:
        domain: ""
        client_id: ""
        client_secret: ""
      auth0:
        domain: ""
        client_id: ""
        client_secret: ""
      azure:
        tenant_id: ""
        client_id: ""
        client_secret: ""
      jwt_signing_key: ""
      session_encryption_key: ""

  # Multi-Tenancy Configuration
  multiTenancy:
    enabled: false
    tenant_identification:
      jwt_claim: "tenant_id"
      header: "X-Tenant-ID"
    isolation:
      data: "schema"  # Options: schema, database, collection
      queue: true
      cache: true
      logging: true
      metrics: true
    quotas:
      rate_limit:
        requests_per_second: 1000
        burst_size: 5000
        by_endpoint:
          "/inference": 500
          "/batch": 100
      concurrent_requests:
        default: 100
      queue:
        max_pending: 10000
        timeout: 300
      models:
        max_loaded: 5
        max_model_size: 50
      storage:
        cache_size_limit: 100
        models_storage_limit: 500
      inference:
        max_tokens: 4096
        max_batch_size: 32
        max_concurrent: 50
    default_tenant: "default"

  # RBAC Configuration
  rbac:
    enabled: false
    default_role: "developer"
    role_claim: "roles"

  # API Key Management
  apiKeys:
    enabled: false
    expiration_days: 365
    rotation_interval_days: 90
    encryption_key: ""
    signing_key: ""

# ============================================================================
# HOOKS
# ============================================================================

hooks:
  preInstall: []
  postInstall: []
  preUpgrade: []
  postUpgrade: []
