{{- if .Values.auth.oauth2.enabled }}
# OAuth2 Secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inferno.fullname" . }}-oauth2-secrets
  namespace: {{ include "inferno.namespace" . }}
  labels:
    {{- include "inferno.labels" . | nindent 4 }}
    component: auth
type: Opaque
stringData:
  {{- with .Values.auth.oauth2.secrets }}
  # Google OAuth2
  OAUTH2_GOOGLE_CLIENT_ID: "{{ .google.client_id | default "" }}"
  OAUTH2_GOOGLE_CLIENT_SECRET: "{{ .google.client_secret | default "" }}"

  # GitHub OAuth2
  OAUTH2_GITHUB_CLIENT_ID: "{{ .github.client_id | default "" }}"
  OAUTH2_GITHUB_CLIENT_SECRET: "{{ .github.client_secret | default "" }}"

  # Okta
  OKTA_DOMAIN: "{{ .okta.domain | default "" }}"
  OAUTH2_OKTA_CLIENT_ID: "{{ .okta.client_id | default "" }}"
  OAUTH2_OKTA_CLIENT_SECRET: "{{ .okta.client_secret | default "" }}"

  # Auth0
  AUTH0_DOMAIN: "{{ .auth0.domain | default "" }}"
  OAUTH2_AUTH0_CLIENT_ID: "{{ .auth0.client_id | default "" }}"
  OAUTH2_AUTH0_CLIENT_SECRET: "{{ .auth0.client_secret | default "" }}"

  # Azure AD
  TENANT_ID: "{{ .azure.tenant_id | default "" }}"
  OAUTH2_AZURE_CLIENT_ID: "{{ .azure.client_id | default "" }}"
  OAUTH2_AZURE_CLIENT_SECRET: "{{ .azure.client_secret | default "" }}"

  # JWT & Session Keys
  JWT_SIGNING_KEY: "{{ .jwt_signing_key | default "" }}"
  SESSION_ENCRYPTION_KEY: "{{ .session_encryption_key | default "" }}"
  {{- end }}
{{- end }}

---
{{- if .Values.auth.apiKeys.enabled }}
# API Key Secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inferno.fullname" . }}-api-keys
  namespace: {{ include "inferno.namespace" . }}
  labels:
    {{- include "inferno.labels" . | nindent 4 }}
    component: api-keys
type: Opaque
stringData:
  # API key encryption key
  API_KEY_ENCRYPTION_KEY: "{{ .Values.auth.apiKeys.encryption_key | default "" }}"

  # API key signing key (for HMAC)
  API_KEY_SIGNING_KEY: "{{ .Values.auth.apiKeys.signing_key | default "" }}"
{{- end }}
