{{- if .Values.monitoring.serviceMonitor.enabled }}
# ServiceMonitor for Prometheus Operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "inferno.fullname" . }}
  namespace: {{ include "inferno.namespace" . }}
  labels:
    {{- include "inferno.labels" . | nindent 4 }}
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      {{- include "inferno.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.prometheus.scrapeInterval }}
      scrapeTimeout: 5s
      path: /metrics
      scheme: http
      relabelings:
        - source_labels: [__meta_kubernetes_pod_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
        - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
          action: replace
          target_label: app
        - source_labels: [__meta_kubernetes_pod_label_environment]
          action: replace
          target_label: environment
        - source_labels: [__meta_kubernetes_pod_label_version]
          action: replace
          target_label: version
{{- end }}
