# Cargo configuration for universal macOS builds

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "target-cpu=apple-m1",
    "-C", "link-arg=-framework", "-C", "link-arg=Metal",
    "-C", "link-arg=-framework", "-C", "link-arg=MetalPerformanceShaders"
]

# Profile-specific optimizations
[profile.release]
lto = "thin"
opt-level = 3

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-cpu=native"]