# Horizontal Pod Autoscaler for Inferno

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inferno
  labels:
    app: inferno
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inferno
  minReplicas: 2
  maxReplicas: 10
  metrics:
    # CPU utilization: scale up at 70%, down at 50%
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    # Memory utilization: scale up at 80%, down at 60%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  # Optional: custom metrics (requires metrics server)
  # - type: Pods
  #   pods:
  #     metric:
  #       name: queue_depth
  #     target:
  #       type: AverageValue
  #       averageValue: "1000"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 50
          periodSeconds: 30
        - type: Pods
          value: 2
          periodSeconds: 30

---

# Vertical Pod Autoscaler (optional, for right-sizing)
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: inferno
  labels:
    app: inferno
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inferno
  updatePolicy:
    updateMode: "Off"  # Change to "Auto" for automatic updates
  resourcePolicy:
    containerPolicies:
      - containerName: inferno
        minAllowed:
          cpu: "500m"
          memory: "1Gi"
        maxAllowed:
          cpu: "4000m"
          memory: "8Gi"
