name: Cargo Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      registry:
        description: 'Registry to publish to'
        required: true
        type: choice
        options:
          - crates-io
          - github
          - both

jobs:
  publish-crates-io:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'release' ||
      (github.event_name == 'workflow_dispatch' &&
       (github.event.inputs.registry == 'crates-io' || github.event.inputs.registry == 'both'))

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Check package
        run: cargo package --no-verify

      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
        continue-on-error: true

  publish-github:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'release' ||
      (github.event_name == 'workflow_dispatch' &&
       (github.event.inputs.registry == 'github' || github.event.inputs.registry == 'both'))

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Configure Cargo for GitHub Packages
        run: |
          mkdir -p ~/.cargo
          cat >> ~/.cargo/config.toml << EOF
          [registries.github]
          index = "https://github.com/ringo380/inferno-cargo-index"
          token = "${{ secrets.GITHUB_TOKEN }}"

          [registry]
          default = "github"
          EOF

      - name: Publish to GitHub Packages
        run: |
          cargo publish --registry github
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}