name: Update Homebrew Formula

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-formula:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get release info
        id: release
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
          else
            VERSION=$(gh release view --json tagName -q .tagName)
          fi
          echo "version=${VERSION#v}" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Calculate SHA256 checksums
        id: checksums
        run: |
          VERSION=${{ steps.release.outputs.version }}

          # Download binaries
          curl -L -o inferno-macos-arm64 \
            "https://github.com/ringo380/inferno/releases/download/v${VERSION}/inferno-macos-arm64"
          curl -L -o inferno-macos-x86_64 \
            "https://github.com/ringo380/inferno/releases/download/v${VERSION}/inferno-macos-x86_64"

          # Calculate checksums
          ARM64_SHA=$(shasum -a 256 inferno-macos-arm64 | awk '{print $1}')
          X86_64_SHA=$(shasum -a 256 inferno-macos-x86_64 | awk '{print $1}')

          echo "arm64_sha=${ARM64_SHA}" >> $GITHUB_OUTPUT
          echo "x86_64_sha=${X86_64_SHA}" >> $GITHUB_OUTPUT

      - name: Update Homebrew formula
        run: |
          VERSION=${{ steps.release.outputs.version }}
          ARM64_SHA=${{ steps.checksums.outputs.arm64_sha }}
          X86_64_SHA=${{ steps.checksums.outputs.x86_64_sha }}

          # Update version and checksums in formula
          sed -i '' "s/version \".*\"/version \"${VERSION}\"/" homebrew/inferno.rb
          sed -i '' "s/ARM64_SHA256_PLACEHOLDER/${ARM64_SHA}/" homebrew/inferno.rb
          sed -i '' "s/X86_64_SHA256_PLACEHOLDER/${X86_64_SHA}/" homebrew/inferno.rb

      - name: Create Homebrew tap repository update
        run: |
          # This would typically push to a separate homebrew-inferno repository
          # For now, we'll commit the updated formula to this repo
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add homebrew/inferno.rb
          git commit -m "chore: update Homebrew formula for v${{ steps.release.outputs.version }}"
          git push