name: NPM Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ringo380'

      - name: Setup Rust for Tauri
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install Tauri dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Update version
        run: |
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#v}
          cd desktop-app
          npm version $VERSION --no-git-tag-version || true

      - name: Install dependencies
        working-directory: desktop-app
        run: npm ci

      - name: Build desktop app
        working-directory: desktop-app
        run: npm run build

      - name: Publish to GitHub Packages
        working-directory: desktop-app
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm-registry:
    runs-on: ubuntu-latest
    if: github.event.release.prerelease == false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Rust for Tauri
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install Tauri dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Update version
        run: |
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#v}
          cd desktop-app
          npm version $VERSION --no-git-tag-version || true

      - name: Install dependencies
        working-directory: desktop-app
        run: npm ci

      - name: Build desktop app
        working-directory: desktop-app
        run: npm run build

      - name: Publish to NPM Registry
        working-directory: desktop-app
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}