name: NPM Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ringo380'

      - name: Check if desktop-app exists
        id: check_app
        run: |
          if [ -f "desktop-app/package.json" ]; then
            echo "ready=true" >> $GITHUB_OUTPUT
            echo "Desktop app package found, proceeding with publish"
          else
            echo "ready=false" >> $GITHUB_OUTPUT
            echo "Desktop app package.json not found, skipping npm publish"
          fi

      - name: Update version
        if: steps.check_app.outputs.ready == 'true'
        run: |
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#v}
          cd desktop-app
          npm version $VERSION --no-git-tag-version --allow-same-version
          echo "Updated package version to $VERSION"

      - name: Publish to GitHub Packages
        if: steps.check_app.outputs.ready == 'true'
        working-directory: desktop-app
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm-registry:
    runs-on: ubuntu-latest
    if: github.event.release.prerelease == false

    steps:
      - uses: actions/checkout@v4

      - name: Check if desktop-app exists
        id: check_app
        run: |
          if [ -f "desktop-app/package.json" ]; then
            echo "ready=true" >> $GITHUB_OUTPUT
            echo "Desktop app package found, proceeding with publish"
          else
            echo "ready=false" >> $GITHUB_OUTPUT
            echo "Desktop app package.json not found, skipping npm publish"
          fi

      - name: Setup Node.js
        if: steps.check_app.outputs.ready == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Update version
        if: steps.check_app.outputs.ready == 'true'
        run: |
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#v}
          cd desktop-app
          npm version $VERSION --no-git-tag-version --allow-same-version
          echo "Updated package version to $VERSION"

      - name: Publish to NPM Registry
        if: steps.check_app.outputs.ready == 'true'
        working-directory: desktop-app
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}